package komunikacija;

import java.io.Serializable;

public enum Operacija implements Serializable {
    PRIJAVI_INSTRUKTORA,
    UCITAJ_POLAZNIKE,
    KREIRAJ_POLAZNIKA,
    PRETRAZI_POLAZNIKE,
    NADJI_POLAZNIKA,
    ZAPAMTI_POLAZNIKA,
    OBRISI_POLAZNIKA,
    UCITAJ_MESTA,
    UCITAJ_CLANSKE_KARTE,
    KREIRAJ_CLANSKU_KARTU,
    PRETRAZI_CLANSKE_KARTE,
    NADJI_CLANSKU_KARTU,
    ZAPAMTI_CLANSKU_KARTU,
    OBRISI_CLANSKU_KARTU,
    UBACI_LICENCU,
    UCITAJ_SPORTOVE,
    UCITAJ_LICENCE,
    UCITAJ_INSTRUKTORE,
}
